title = "Media Info"

[media]
# File path
# Please Input for MOV or MP4 file path
path = "./media/test.mp4"

[trim_info]
# List of time information used in the trimming process
# time_list = [[start_time1, end_time1],[start_time2, end_time2],...,[start_timeN, end_timeN])
time_list = [[0, 10], [11, 20], [30, 60]]
# If an empty list is created, the specified parsing process will create time information.
# time_list = []